### ISSUE TITLE
No longer appears to work ("User not logged in")

### ISSUE THREAD

**Issue by james1236** [vaclavsvejcar/ytb-history-scraper#2]
I think YouTube might have changed something since you made this tool.

I opened a new YouTube window, opened chrome devtools and copied the text from running `document.cookie` in the console to the `cookies.txt` file but I just get this message:

> User is not logged in, exiting...

Am I not getting the cookie properly or does this tool not work anymore? Thanks!

**Comment by vaclavsvejcar** [comment]
Hello @james1236 ,

unfortunately it seems that YouTube changed something on the website so the script doesn't work anymore. I noticed it some time ago and spent some time trying to fix it, but cannot really figure out what needs to be changed. Problem is that this script doesn't use any API (because there's no such one), but instead scrapes the website with cookies copied from real browser, trying to use the same session. So the fix should be about to find correct combination of cookies and maybe some other stuff (user agent, some local storage??) that would work. I'll try to fix this in some spare time, or eventually, would you like to work on it?

**Comment by vaclavsvejcar** [comment]
@james1236 I found nasty bug where YouTube cookies were not parsed correctly when the cookie value contains the _=_ (equals sign). This is now fixed and the app works for me correctly. You mentioned that you grab your cookies using `document.cookie`, right? Problem with this approach is that is cannot read _HttpOnly_ cookies, so you might be actually missing some of them (see https://stackoverflow.com/a/1022119/2028789). Can you please try it again, using the way described in _README_? I was using _Mozilla Firefox_, but I guess it should be similar for any other browser.

**Comment by james1236** [comment]
Thank you, it's logging in successfully now! Great tool, please add that you were using Firefox to the README since there is no similarly easy way to copy the whole raw text cookie in chrome. I'm encountering a new issue but I'll open another ticket for that
